### ISSUE TITLE
Baobab example?

### ISSUE THREAD

**Issue by davidmoshal** [cerebral/cerebral-boilerplate#8]
Just noticed that the boilerplate doesn't show usage of Baobab.
Dave

**Comment by Guria** [comment]
Follow to cerebral-todomvc repo.

**Comment by davidmoshal** [comment]
didn't see one there either, unless I'm on the wrong branch?

**Comment by christianalfoni** [comment]
Hm, usage in what way @davidmoshal ? :)

**Comment by edgesoft** [comment]
@davidmoshal The addons is used in the boilerplate. Check out https://github.com/cerebral/cerebral-model-baobab

**Comment by Guria** [comment]
@davidmoshal baobab is not used directly but as "backend" for cerebral state store. Methods to work with it exposed to actions. See state docs on website

**Comment by davidmoshal** [comment]
OK, thanks, will take a look.
